application: dipen-pradhan
version: 1
runtime: php55
api_version: 1

handlers:
# - url: /.*
#   script: helloworld.php

- url: /
  static_files: index.html
  upload: index.html

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /files
  static_dir: files
